# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=9)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_e', models.CharField(max_length=10)),
                ('fecha_s', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=9)),
                ('adultos', models.IntegerField(default=0)),
                ('ninos', models.IntegerField(default=0)),
            ],
        ),
    ]
