# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='habitacion',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
